file_format: "1"
id: totem
name: TOTEM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: 
  - seeeduino_xiao_ble
  - pro_micro
exposes:
  - i2c_oled
features:
  - keys
siblings:
  - totem_left
  - totem_right
  - totem_dongle
